spring:
  application:
    name: user-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/user_manager
    username: postgres
    password: 4277
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info


